version: "3.5"
services:
  go-notifications:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-notify
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .env:/.env
    networks:
      - app

networks:
  app:
    name: strategraph_cluster
    driver: bridge
    external: true